### PR TITLE
Fix changed locators for footer

### PR DESCRIPTION
**Pull request by bobsilverberg**
PEP8 fixes too

This fixes the failures as seen at https://webqa-ci.mozilla.com/job/marketplace.dev.sanity.saucelabs/32/

@m8ttyB / @rbillings r?

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@mstriemer would you be available for a quick r? for these test fixes? Thanks!

**Comment by ngokevin** [comment]
r+

**Comment by stephendonner** [comment]
Thx you two; merging in to fix bustage.

**Comment by bobsilverberg** [comment]
Yes, thanks @ngokevin :)

**Pull request merged**
