### PR TITLE
Update locators and remove unused code

### PR DESCRIPTION
**Pull request by bobsilverberg**
These changes are required as a result of https://github.com/mozilla/fireplace/commit/0a06b083603094f6702b93997a4c9f0b4ddc49a2
Fixes issue #721

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Adhocs are running and I am seeing some failures (although everything passed for me locally), so hold off reviewing this until I check out the adhoc failures.

**Comment by bobsilverberg** [comment]
The desktop consumer pages adhoc passed: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/marketplace.adhoc/51/

The mobile one: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/marketplace.mobile.adhoc/27/ is having issues unrelated to this PR.

I think this is ready for review, @davehunt, and I am confident that it is okay, although you might want to at least run the mobile tests yourself locally as a double-check.

**Comment by mstriemer** [comment]
@spasovski Looks like you changed these selectors. Do these updates look good?

**Comment by spasovski** [comment]
@mstriemer yes and sorry about that. It's a better idea to target by class name rather than element in this case anyway.

**Comment by davehunt** [comment]
r+

**Comment by stephendonner** [comment]
Thx, all; let's get this in to fix test bustage

**Pull request merged**
