### PR TITLE
Migrate to pytest-selenium

### PR DESCRIPTION
**Pull request by davehunt**
@bobsilverberg r?

### CODE REVIEW

**Comment by davehunt** [comment]
Adhoc builds:

* http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/marketplace.adhoc.pytest-selenium/6/
* http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/marketplace.mobile.adhoc.pytest-selenium/6/

Note that this should not be merged until the Jenkins jobs are updated for pytest-selenium.

**Comment by davehunt** [comment]
Now that @bobsilverberg is working on another project, I wonder if @m8ttyB, @rbillings or @stephendonner may be able to review this? It's quite a large change, so I'm concerned that it will rot easily.

**Comment by rbillings** [comment]
Changes look good and desktop tests pass. R+

**Comment by stephendonner** [comment]
r+ from me too, FWIW (I boned up on and have compared to past pytest-mozwebqa -> pytest-selenium conversions, and this looks straight-forward).

Holding off on merging until either @davehunt gets a chance to update Jenkins, or one of us figures it out :-)

**Pull request merged**
