### PR TITLE
Remove unused Paypal methods and classes

### PR DESCRIPTION
**Pull request by davehunt**
As far as I can tell this is not used anywhere... It even uses the old style of credentials, which I'm not even sure works any more... @krupa r?

### CODE REVIEW

**Comment by davehunt** [comment]
Adhoc builds:
* [marketplace-dev.allizom.org, mobile](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/marketplace.mobile.adhoc/45/) - one known failure, see #746 
* [marketplace-dev.allizom.org, desktop](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/marketplace.adhoc/86/) - developer hub failures, similar to what we're seeing without this patch, I think it's safe to ignore them here
* [marketplace.allizom.org, mobile](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/marketplace.mobile.adhoc/47/) - one known failure, see #746 
* [marketplace.allizom.org, desktop](http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/marketplace.adhoc/87/) - passed

@bobsilverberg r?

**Comment by bobsilverberg** [comment]
This looks good, @davehunt, but is it complete? It looks like another method in `base_test.py`, `_open_payment_settings_page` is never used. Should that be removed too, or do you see that as a separate patch?

**Comment by davehunt** [comment]
@bobsilverberg I've removed a little more. To be honest I was only removing this because it blocks migrating to pytest-selenium. Rather than try to migrate this code, I saw it was unused, hence the patch. I'm sure there's more we can remove, but it can be taken care of separately.

**Comment by bobsilverberg** [comment]
LGTM @davehunt, and I understand that there may be (much) more to remove. r+

**Pull request merged**
