### PR TITLE
fix test_that_application_page_contains_proper_objects (supp...

### PR DESCRIPTION
**Pull request by AndreiH**
...ort email text/link) #601

### CODE REVIEW

**Comment by AndreiH** [comment]
@stephendonner @bobsilverberg  r?

**Comment by bobsilverberg** [comment]
LGTM. r+ from me, but @krupa can you please give this a quick r? as well to confirm that simply removing those checks is ok?

**Comment by clouserw** [comment]
The logic on the site is at least one of the website or the email must be present.

**Comment by AndreiH** [comment]
So how can we address this issue @clouserw ?

**Comment by AndreiH** [comment]
ok, talked to @krupa and she said to " check if  support website exists. if not, support email id exists.  if neither exists, it is a bug"

**Comment by stephendonner** [comment]
Thx @krupa + @AndreiH - so we need to update the pull, then, right?

**Comment by AndreiH** [comment]
I think this should do it @stephendonner , works for me locally.

**Pull request merged**
