### PR TITLE
Update tests to use FXApom

### PR DESCRIPTION
**Pull request by AndreiH**
this is ready for review! Please see adhoc here 
CONSUMER PAGES: http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.DEV.saucelabs.fxapom/

DEVELOPER HUB:
http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.DEV.developer_hub.saucelabs.fxapom/

### CODE REVIEW

**Comment by AndreiH** [comment]
@bobsilverberg can you help me investigate this? I don't know why I get this error when trying to create an account.

**Comment by bobsilverberg** [comment]
@AndreiH Looking into this now.

**Comment by bobsilverberg** [comment]
@AndreiH I am not seeing this issue. I can create an account via faxpom. Try reinstalling everything. Maybe PyFxA needs an update.

**Comment by AndreiH** [comment]
I am going to close this PR and open a new one. This is kinda old and I wanna start fresh.

**Pull request closed without merging**
