### PR TITLE
Add Payment test for Desktop

### PR DESCRIPTION
**Pull request by AndreiH**
This is for https://github.com/mozilla/marketplace-tests/issues/606

### CODE REVIEW

**Comment by AndreiH** [comment]
I gave issues with this because the pin is not sent to the input field and I can't figure out why.
The <code>send_keys</code> method passes but the pin is not inserted
@bobsilverberg can you help taking a look? Same thing happens in https://github.com/mozilla/marketplace-tests/issues/618

**Comment by bobsilverberg** [comment]
Closing and reopening to see what Travis says about pep8 issues.

**Comment by bobsilverberg** [comment]
@AndreiH I encountered the same issue, and it's quite baffling. I worked on it for a few hours today and was able to get it to pass some of the time when I ran the code through the interactive debugger, but never from the command line. I tried all sorts of different things with waits and sleeps but no dice. I will likely ask @davehunt if he can take a look and see if he has any ideas.

What is particularly baffling is that the server side code seems to be the same as for Firefox OS, where the automation is working.

**Comment by bobsilverberg** [comment]
This is being replaced by PR #621

**Pull request closed without merging**
