### PR TITLE
Change maximize window to set specific window dimensions

### PR DESCRIPTION
**Pull request by bobsilverberg**
Some of our tests will not display the expected elements unless the browser window is at least 1050 pixels wide. So, rather than simply maximizing the window, we should set it to a specific size that we know will work.

@AndreiH r?

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@davehunt I guess if we implement this then we don't even need to force Saucelabs to use a particular screen resolution, correct?

**Comment by davehunt** [comment]
So did this work? I'm not against setting a high resolution, especially if it means the Sauce videos will contain the full screen. It does make sense to me that the test/suite sets the browser to the minimum size. It might make sense to check the current size (if we can) to determine if resizing is needed.

**Comment by AndreiH** [comment]
I tested this locally and this method works fine.
Wanted to see what happens if the VM has a lower resolution, so I changed mine to 800x600, but this did  not affected the method. The only thing that I am seeing is that it might affect the screenshots (only if there is a lower resolution on VMs) just half of Firefox window is visible.
I am giving a r+ for this, works fine, so feel free to merge if everything is alright with you. :+1:

**Comment by bobsilverberg** [comment]
@davehunt I tested it and it does indeed work. The test passes on Saucelabs if I run with this branch and remove `--capability=screen-resolution:1280x1024`. I also updated the code to check whether resizing is needed. I'm not sure why the catchall try is in there. I guess sometimes the command can fail? It seems a bit dangerous to me to leave it in there. What do you think?

**Comment by davehunt** [comment]
Yeah, let's see if we can remove the try/except... I also feel like we could make this more implicit, but wouldn't waste much thought on it for now. Be warned that if the window is larger than the screen then videos in Sauce Labs will likely be affected (the browser will be partly off-screen). Screenshots should be fine though.

**Comment by bobsilverberg** [comment]
Thanks @davehunt. I removed the `try`. Let's see if it is happy without it. Merging this on 2 r+s

**Pull request merged**
