### PR TITLE
Add Payment test for Desktop

### PR DESCRIPTION
**Pull request by bobsilverberg**
This replaces PR #617, which @AndreiH created. This includes a fix for the PIN entry issue.

This addresses issue #606 

Note that the test still fails after purchasing the app because the details page does not update (the spinner keeps spinning). A bug should be opened about that.

### CODE REVIEW

**Comment by AndreiH** [comment]
@bobsilverberg the test fails at the end because we need to find a better way to check that the Payment was a success. As you can see, after the payment is complete a Firefox pop up appears to continue installing the app, and the spinner is expected to still be there [1]
We need to find another way to assert that the payment was a success.

[1] http://tinypic.com/r/6fwena/8

**Comment by bobsilverberg** [comment]
This looks like it may be a blocker for testing that the app is installed. It is possible we could get around this using Marionette, which might allow us to finish the app install process, but that raises technical issues. It might mean creating a separate suite for tests that need Marionette.

Another option, which might be considered valid for this test case, would be to simply verify that the Buy button is displayed, and then verify that the payment window closes. This might imply that the payment was successful, and perhaps we can ignore whether the app gets successfully installed or not.

@krupa What do you think?

**Comment by krupa** [comment]
Let us make sure that the payment window closes and that should suffice.

**Comment by bobsilverberg** [comment]
Ok, I have updated the test to check that the payment window has closed and we are back at the details page for the app.

@AndreiH r?

**Comment by bobsilverberg** [comment]
I figured out that we can do even better. The app status, which is defined as the set of classes on the install button, gets updated with `purchased` after a successful purchase, so I am checking that now. :)

**Comment by krupa** [comment]
That's awesome, Bob! Thanks.

**Comment by AndreiH** [comment]
Ok, I think this is the best way to check that app has been purchased. 
The changes look good, but just realized that this test will fail on Stage as there is no Zippy app on stage.
What do you think is the best way to resolve this?
@krupa @bobsilverberg ?

**Comment by stephendonner** [comment]
I assume we still want and need this -- @bobsilverberg @krupa @davehunt can you three work together on this, if so?  Thanks.

**Comment by bobsilverberg** [comment]
Hey @stephendonner, sorry for dropping the ball on this. I think the PR was ready to merge, except for some issues with availability of the test app on different platforms. I have resurrected it now and tried to test it, but found that the test app "Test Zippy With Me" is listed as "not available for your platform", so I cannot install it.

@krupa can you help me resolve this?

**Comment by krupa** [comment]
fixed @ https://marketplace-dev.allizom.org/app/test-zippy-with-me/

**Comment by bobsilverberg** [comment]
Thanks @krupa!

This is now ready to review. @rbillings or @m8ttyB, care to r?

**Comment by rbillings** [comment]
The changes look good & the test passes locally. R+

**Comment by bobsilverberg** [comment]
Thanks @rbillings. Merging!

**Comment by davehunt** [comment]
This is failing in Jenkins and for me locally. I raised https://bugzilla.mozilla.org/show_bug.cgi?id=1161559

**Pull request merged**
